#====================================================
# spring boot配置
#
# 完整文档：
#====================================================

spring:
  profiles:
    # 测试dev
    active: dev
    # 生产prod
  # active: prod
  application:
    name: config-server
